apiVersion: v1
kind: Template
metadata:
  name: ${APP_NAME}
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APP_NAME}
        build: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      output:
        pushSecret:
          name: artifactory-image
        to:
          kind: DockerImage
          name: 'artifactory/${APP_NAME}/${APP_NAME}:latest'
      source:
        git:
          ref: ${BRANCH_NAME}
          uri: ${SOURCE_REPOSITORY_URL}
        sourceSecret:
          name: ${SOURCE_SECRET_NAME}
        type: Git
      strategy:
        type: Docker
parameters:
  - name: APP_NAME
    displayName: Application Name
    description: Unique application name
    value: ms-push
    required: true
  - name: SOURCE_REPOSITORY_URL
    displayName: SOURCE_REPOSITORY_URL
    description: SOURCE_REPOSITORY_URL
    value: http://bitbucket/bex/bex-ms-push.git
    required: true
  - name: BRANCH_NAME
    displayName: BRANCH_NAME
    description: BRANCH_NAME
    value: master
    required: true
  - name: SOURCE_SECRET_NAME
    displayName: SOURCE_SECRET_NAME
    description: SOURCE_SECRET_NAME
    value: bitbucket-builder
    required: true